Table clientes {
  id_cliente int [pk, increment]
  nome varchar(100) [not null]
  email varchar(100) [unique]
  telefone varchar(20)
  data_nascimento date
}

Table jogos {
  id_jogo int [pk, increment]
  titulo varchar(150) [not null]
  genero varchar(50) [not null]
  classificacao_indicativa varchar(10) [not null]
  plataforma varchar(50) [not null]
}

Table locacoes {
  id_locacao int [pk, increment]
  cliente_id int [not null, ref: > clientes.id_cliente]
  data_retirada date [not null]
  data_prevista_devolucao date [not null]
  data_devolucao_efetiva date
}

Table itens_locacao {
  locacao_id int [not null, ref: > locacoes.id_locacao]
  jogo_id int [not null, ref: > jogos.id_jogo]
  
  indexes {
    (locacao_id, jogo_id) [pk]
  }
}
